# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: <!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>

<body>
<table width="200" border="1">
  <tbody>
    <tr>
      <th scope="row">SUPPLY CHAIN MANAGEMENT&nbsp;</th>
      <td>NQF 5&nbsp;</td>
    </tr>
    <tr>
      <th scope="row">TRANSPOTATION MANAGEMENT</th>
      <td>&nbsp;NQF 6</td>
    </tr>
    <tr>
      <th scope="row">IT: SOFTWARE DEVELOPMENT&nbsp;</th>
      <td>&nbsp;NQF 7</td>
    </tr>
    <tr>
      <th scope="row">BUSINESS ANALYST&nbsp;</th>
      <td>&nbsp;NQF 6</td>
    </tr>
    <tr>
      <th scope="row">CALL CENTER&nbsp;</th>
      <td>&nbsp;NQF 2</td>
    </tr>
    <tr>
      <th scope="row">GRAPHIC DESIGN&nbsp;</th>
      <td>&nbsp;NQF 4</td>
    </tr>
    <tr>
      <th scope="row">MACHENICAL ENG&nbsp;</th>
      <td>&nbsp;NQF 6</td>
    </tr>
    <tr>
      <th scope="row">B.ed&nbsp;</th>
      <td>&nbsp;B</td>
    </tr>
    <tr>
      <th scope="row">PYTHON ( in demand)</th>
      <td>&nbsp;CERTIFICATE</td>
    </tr>
    <tr>
      <th scope="row">&nbsp;JAVA</th>
      <td>&nbsp;CERTIFICATE</td>
    </tr>
    <tr>
      <th scope="row">coming soon!&nbsp;</th>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th scope="row">coming soon! &nbsp;</th>
      <td>&nbsp;</td>
    </tr>
  </tbody>
</table>
<h2>COURSES AVAILABLE </h2>
<p>&nbsp;</p>
</body>
</html>
          echo Add other actions to build,
          echo test, and deploy your project.
